version: 2

sources:
  - name: xkcd_raw
    database: xkcd_db
    schema: public
    tables:
      - name: raw_xkcd_comics
        description: "Raw data for xkcd comics, sourced from the xkcd API."
        loaded_at_field: inserted_at

